"""Inventory and Production domain boundary."""

from .expiry_alerts import (
    EXPIRY_ALERT_RULE_KEY,
    EXPIRY_ALERT_WINDOW_DAYS,
    ExpiryAlertState,
    ExpiryAlertValidationError,
    acknowledge_alert,
    requires_expiry_alert,
)
from .production import (
    ProductionValidationDetail,
    ProductionValidationError,
    StockAllocation,
    StockLot,
    ValidatedProductionBatch,
    allocate_stock,
    validate_production_batch,
)
from .transfers import (
    TransferState,
    TransferValidationDetail,
    TransferValidationError,
    ValidatedTransferRequest,
    approve_transfer,
    dispatch_transfer,
    receive_transfer,
    validate_transfer_request,
)
from .waste import (
    HIGH_VALUE_THRESHOLD,
    ValidatedWasteSubmission,
    WasteState,
    WasteValidationDetail,
    WasteValidationError,
    approve_waste,
    classify_waste,
    validate_waste_submission,
)

__all__ = [
    "ProductionValidationDetail",
    "ProductionValidationError",
    "StockAllocation",
    "StockLot",
    "ValidatedProductionBatch",
    "allocate_stock",
    "validate_production_batch",
    "TransferState",
    "TransferValidationDetail",
    "TransferValidationError",
    "ValidatedTransferRequest",
    "approve_transfer",
    "dispatch_transfer",
    "receive_transfer",
    "validate_transfer_request",
    "HIGH_VALUE_THRESHOLD",
    "ValidatedWasteSubmission",
    "WasteState",
    "WasteValidationDetail",
    "WasteValidationError",
    "approve_waste",
    "classify_waste",
    "validate_waste_submission",
    "EXPIRY_ALERT_RULE_KEY",
    "EXPIRY_ALERT_WINDOW_DAYS",
    "ExpiryAlertState",
    "ExpiryAlertValidationError",
    "acknowledge_alert",
    "requires_expiry_alert",
]
