services:
  postgres:
    ports: !reset []

  api:
    environment:
      GL_ENVIRONMENT: integration
      TEST_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports: !override
      - "127.0.0.1:58000:8000"

  migrate:
    environment:
      GL_ENVIRONMENT: integration

  seed:
    environment:
      GL_ENVIRONMENT: integration

  web:
    ports: !override
      - "127.0.0.1:53000:3000"
