services:
  migrate:
    environment:
      GL_ENVIRONMENT: qa

  api:
    environment:
      GL_ENVIRONMENT: qa

  worker:
    environment:
      GL_ENVIRONMENT: qa

  web:
    environment:
      GL_ENVIRONMENT: qa
